#server.port=8090
#spring.application.name=inventory-service
spring:
  application:
    name: inventory-service
  profiles:
    active: git
  config:
    import: "optional:configserver:http://localhost:8888"
